name: 'Gigalixir Action'
description: 'Deploy to Gigalixir'
inputs:
  GIGALIXIR_USERNAME:
    description: 'Your Gigalixir username'
    required: true
  GIGALIXIR_PASSWORD:
    description: 'Your Gigalixir password'
    required: true
  SSH_PRIVATE_KEY:
    description: 'Your ssh private key that is paired with a public key that is uploaded to Gigalixir'
    required: true
  GIGALIXIR_APP:
    description: 'Your gigalixir app name'
    required: true
  MIGRATIONS:
    description: 'Configuration for migrations'
    required: true
    default: true
  MIGRATION_APP_NAME:
    description: 'Name of the app that contains migrations (useful for umbrella apps)'
    required: false
    default: ""
  APP_SUBFOLDER:
    description: 'Subfolder of your app'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
