name: 'Gigalixir Action'
description: 'Deploy to Gigalixir'
inputs:
  APP_SUBFOLDER:
    description: 'Subfolder of your app'
    required: false
  GIGALIXIR_APP:
    description: 'Your gigalixir app name'
    required: true
  GIGALIXIR_CLEAN:
    description: 'Extra flag you can pass to clean your cache before building'
    required: false
    default: false
  GIGALIXIR_USERNAME:
    description: 'Your Gigalixir username'
    required: true
  GIGALIXIR_API_KEY:
    description: 'Your Gigalixir API key -- either this option or GIGALIXIR_PASSWORD should be used'
    required: false
  GIGALIXIR_PASSWORD:
    description: 'Your Gigalixir password -- either this option or GIGALIXIR_API_KEY should be used'
    required: false
  MIGRATIONS:
    description: 'Configuration for migrations'
    required: true
    default: true
  SSH_PRIVATE_KEY:
    description: 'Your ssh private key that is paired with a public key that is uploaded to Gigalixir'
    required: ${MIGRATIONS}

runs:
  using: 'node12'
  main: 'dist/index.js'
